# Copyright (c) 2020 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "OCI CIS Landing Zone Pre-Config Stack"
stackDescription: "A Resource Manager Stack to pre configure a tenancy for Landing Zone deployment."
schemaVersion: 1.1.0
version: "0.0.1"
locale: "en"

variableGroups:
  - title: "Environment"
    variables:
      - "home_region"
      - "unique_prefix"
      
  - title: "Top Compartment"
    variables:
      - "enclosing_compartment_name"
      - "existing_enclosing_compartment_parent_ocid"

  - title: "Provisioning Group"
    variables:
      - "use_existing_provisioning_group"
      - "existing_provisioning_group_name"
      
  - title: "Landing Zone Policies & Groups"
    variables:
      - "create_tenancy_level_policies"
      - "create_lz_groups"
      - "existing_iam_admin_group_name"
      - "existing_cred_admin_group_name"
      - "existing_security_admin_group_name"
      - "existing_network_admin_group_name"
      - "existing_appdev_admin_group_name"
      - "existing_database_admin_group_name"
      - "existing_auditor_group_name"
      - "existing_announcement_reader_group_name"

  - title: "Hidden Variables"
    visible: false
    variables:
      - "tenancy_ocid"
      - "user_ocid"
      - "fingerprint"
      - "private_key_path"
      - "private_key_password"

variables:

  home_region:
    type: oci:identity:region:name
    title: "Home region"
    description: "The tenancy home region."
    required: true
  
  unique_prefix:
    type: string
    title: "Unique prefix"
    minLength: 1
    maxLength: 8
    pattern: "^[A-Za-z][A-Za-z0-9]{1,7}$"
    description: "A unique prefix added to all resource names created by this module."
    required: true

  enclosing_compartment_name:
    type: string
    title: "Enclosing compartment name"
    description: "The name of the enclosing compartment for the Landing Zone compartments. If not provided, the compartment is created with a default name."
    required: false
  
  existing_enclosing_compartment_parent_ocid:
    type: string
    title: "Parent compartment OCID"
    description: "It defines where the enclosing compartment is created. If not provided, the enclosing compartment is created in the root compartment."
    required: false

  use_existing_provisioning_group:
    type: boolean
    title: "Use existing provisioning group?"
    description: "Whether or not an existing group is to be used for Landing Zone provisioning. If false, a group is created with a default name."
    default: false  

  existing_provisioning_group_name:
    type: string
    title: "Existing provisioning group name"
    description: "The name of an existing group to be used for Landing Zone provisioning. Ignored if use_existing_provisioning_group is false."
    required: false
    visible :  use_existing_provisioning_group 
  
  create_tenancy_level_policies:
    type: boolean
    title: "Create Landing Zone tenancy level policies?"
    description: "Whether or not tenancy level policies for Landing Zone groups are created."
    default: true
    required: true

  create_lz_groups:
    type: boolean
    title: "Create Landing Zone groups?"
    description: "Whether or not Landing Zone groups are created. If false, existing group names should be provided."
    default: true  
    required: true
  
  existing_iam_admin_group_name:
    type: string
    title: "Existing IAM admin group name"
    description: "Existing group to which IAM management policies will be granted to."
    visible: ${!create_lz_groups}
    required: false

  existing_cred_admin_group_name:
    type: string
    title: "Existing credentials admin group name"
    description: "Existing group to which credentials management policies will be granted to."
    visible: ${!create_lz_groups}
    required: false

  existing_security_admin_group_name:
    type: string
    title: "Existing security admin group name"
    description: "Existing group to which security management policies will be granted to."
    visible: ${!create_lz_groups}
    required: false

  existing_network_admin_group_name:
    type: string
    title: "Existing network admin group name"
    description: "Existing group to which network management policies will be granted to."
    visible: ${!create_lz_groups}
    required: false

  existing_appdev_admin_group_name:
    type: string
    title: "Existing application development admin group name"
    description: "Existing group to which application development management policies will be granted to."
    visible: ${!create_lz_groups}
    required: false

  existing_database_admin_group_name:
    type: string
    title: "Existing database admin group name"
    description: "Existing group to which database management policies will be granted to."
    visible: ${!create_lz_groups}
    required: false

  existing_auditor_group_name:
    type: string
    title: "Existing auditors group name"
    description: "Existing group to which auditing policies will be granted to."
    visible: ${!create_lz_groups}
    required: false

  existing_announcement_reader_group_name:
    type: string
    title: "Existing annoucement readers group name"
    description: "Existing group to which annoucement reading policies will be granted to."
    visible: ${!create_lz_groups}
    required: false

  # Hidden variables
  tenancy_ocid:
    type: string

  user_ocid:
    type: string

  fingerprint:
    type: string

  private_key_path:
    type: string

  private_key_password:
    type: password
