# Copyright (c) 2021 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "Pre-configuration for CIS (Center for Internet Security) OCI Landing Zone Quick Start"
stackDescription: "This stack pre-configures a tenancy for CIS Landing Zones deployment in OCI. It creates compartments, groups, groups policies and dynamic groups, hence meant to be executed by users with the required permissions at the Root compartment. Only required when users that will deploy the CIS Landing Zone do NOT have the required permissions to create such resources at the Root compartment level. For details on the supported variables please see https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/blob/main/VARIABLES.md#pre_config_input_variables"
description: "This stack pre-configures a tenancy for CIS Landing Zones deployment in OCI. It creates compartments, groups, groups policies and dynamic groups, hence meant to be executed by users with the required permissions at the Root compartment. Only required when users that will deploy the CIS Landing Zone do NOT have the required permissions to create such resources at the Root compartment level."
schemaVersion: 1.1.0
version: "2.7.0"
locale: "en"

# URL of CIS Landing Zone logo icon used on Application Information tab.
logoUrl: "https://objectstorage.us-ashburn-1.oraclecloud.com/p/taf6kC9fSJyQDNSYbxvqxS_JsdnSu56oFZ3-1h5vI7-WfJUv77mplChopLxZPePW/n/ociateam/b/cis-landing-zone/o/landing_zone_130.png"

variableGroups:
  - title: "Environment"
    variables:
      - "home_region"
      - "unique_prefix"
      - "advanced_options"

  - title: "Compartments"
    variables:
      - "enclosing_compartment_names"
      - "existing_enclosing_compartments_parent_ocid"
    visible: advanced_options  

  - title: "Groups"
    variables:
      - "use_existing_provisioning_group"
      - "existing_provisioning_group_name"
      - "use_existing_groups"
      - "existing_iam_admin_group_name"
      - "existing_cred_admin_group_name"
      - "existing_security_admin_group_name"
      - "existing_network_admin_group_name"
      - "existing_appdev_admin_group_name"
      - "existing_database_admin_group_name"
      - "existing_auditor_group_name"
      - "existing_announcement_reader_group_name"
      - "existing_exainfra_admin_group_name"
      - "existing_cost_admin_group_name"
      - "existing_storage_admin_group_name"
    visible: advanced_options  
  
  - title: "Dynamic Groups"
    variables:
      - "deploy_dynamic_groups"
    visible: advanced_options

  - title: "Policies"
    variables:
      - "grant_services_policies"
    visible: advanced_options

  - title: "Hidden Variables"
    visible: false
    variables:
      - "tenancy_ocid"
      - "user_ocid"
      - "fingerprint"
      - "private_key_path"
      - "private_key_password"

variables:
  home_region:
    type: oci:identity:region:name
    title: "Home Region"
    description: "The tenancy home region."
    required: true
  
  unique_prefix:
    type: string
    title: "Unique Prefix"
    minLength: 0
    maxLength: 15
    pattern: "^$|[A-Za-z][A-Za-z0-9]{0,15}$"
    description: "If provided, a unique prefix across the tenancy that is added to all resource names created by this stack."
  
  advanced_options:
    type: boolean
    title: "Show Advanced Options"
    description: "If you don't change any of the advanced options, the following is created: 1) one compartment named with 'top-cmp' suffix in the root compartment; 2) one set of policies for Landing Zone(s) required services in the root compartment; 3) one group to provision the Landing Zone(s); 4) one set of groups to manage the Landing Zone(s); 5) one set of dynamic groups. For details, check the <a href=\"https://www.ateam-oracle.com/tenancy-pre-configuration-for-deploying-cis-oci-landing-zone-as-a-non-administrator\">Landing Zone Pre-config documentation</a>."
    default: false

  enclosing_compartment_names:
    type: array
    items:
      type: string
    uniqueItems: true
    title: "Enclosing Compartment Names"
    description: "The names of the enclosing compartments that will be created to hold Landing Zone compartments. If not provided, one compartment is created with default name ending in '-top-cmp'. (Type the name and hit enter to enter multiple values)."
    required: false
    default: []

  existing_enclosing_compartments_parent_ocid:
    type: oci:identity:compartment:id
    title: "Existing Enclosing Compartments Parent"
    description: "The enclosing compartments parent compartment. It defines where enclosing compartments are created. If not provided, the enclosing compartments are created in the root compartment."
    required: false
  
  grant_services_policies:
    type: boolean
    title: "Grant Services Policies?"
    description: "Whether services policies should be granted. If these policies already exist in the root compartment, set it to false for avoiding policies duplication. Services policies are required by some OCI services, like Cloud Guard, Vulnerability Scanning and OS Management."
    default: true
  
  use_existing_provisioning_group:
    type: boolean
    title: "Use Existing Group for Provisioning the Landing Zone?"
    description: "Whether an existing group should be used for Landing Zone provisioning. If unchecked, one group is created for each compartment specified in \"Enclosing Compartment Names\"."
    default: false

  existing_provisioning_group_name:
    type: oci:identity:groups:id
    dependsOn:
      compartmentId: ${tenancy_ocid}
    title: "Existing Group Name for Provisioning the Landing Zone"
    description: "The name of an existing group to be used for provisioning all resources in the compartments specified in \"Enclosing Compartment Names\"."
    visible :  use_existing_provisioning_group
      
  use_existing_groups:
    type: boolean
    title: "Use Existing Groups for Managing the Landing Zone?"
    description: "Whether existing groups should be reused for managing the Landing Zone. When unchecked, one set of groups is created for each compartment specified in \"Enclosing Compartment Names\". If checked, existing group names must be provided and this single set will be able to manage resources in all those compartments."
    default: false
    required: true
  
  existing_iam_admin_group_name:
    type: oci:identity:groups:id
    dependsOn:
      compartmentId: ${tenancy_ocid}
    title: "Existing IAM admin group name"
    description: "Existing group to which IAM management policies will be granted to."
    visible: use_existing_groups
    
  existing_cred_admin_group_name:
    type: oci:identity:groups:id
    dependsOn:
      compartmentId: ${tenancy_ocid}
    title: "Existing credentials admin group name"
    description: "Existing group to which credentials management policies will be granted to."
    visible: use_existing_groups
      
  existing_security_admin_group_name:
    type: oci:identity:groups:id
    dependsOn:
      compartmentId: ${tenancy_ocid}
    title: "Existing security admin group name"
    description: "Existing group to which security management policies will be granted to."
    visible: use_existing_groups
      
  existing_network_admin_group_name:
    type: oci:identity:groups:id
    dependsOn:
      compartmentId: ${tenancy_ocid}
    title: "Existing network admin group name"
    description: "Existing group to which network management policies will be granted to."
    visible: use_existing_groups
      
  existing_appdev_admin_group_name:
    type: oci:identity:groups:id
    dependsOn:
      compartmentId: ${tenancy_ocid}
    title: "Existing application development admin group name"
    description: "Existing group to which application development management policies will be granted to."
    visible: use_existing_groups
      
  existing_database_admin_group_name:
    type: oci:identity:groups:id
    dependsOn:
      compartmentId: ${tenancy_ocid}
    title: "Existing database admin group name"
    description: "Existing group to which database management policies will be granted to."
    visible: use_existing_groups
      
  existing_auditor_group_name:
    type: oci:identity:groups:id
    dependsOn:
      compartmentId: ${tenancy_ocid}
    title: "Existing auditors group name"
    description: "Existing group to which auditing policies will be granted to."
    visible: use_existing_groups
      
  existing_announcement_reader_group_name:
    type: oci:identity:groups:id
    dependsOn:
      compartmentId: ${tenancy_ocid}
    title: "Existing announcement readers group name"
    description: "Existing group to which announcement reading policies will be granted to."
    visible: use_existing_groups
      
  existing_exainfra_admin_group_name:
    type: oci:identity:groups:id
    dependsOn:
      compartmentId: ${tenancy_ocid}
    title: "Existing admin group name for Exadata Cloud Service infrastructure"
    description: "Existing group to which Exadata Cloud Service infrastructure management policies will be granted to."
    visible: use_existing_groups

  existing_cost_admin_group_name:
    type: oci:identity:groups:id
    dependsOn:
      compartmentId: ${tenancy_ocid}
    title: "Existing Cost Admin group name"
    description: "Existing group to which Cost management policies will be granted to."
    visible: use_existing_groups

  existing_storage_admin_group_name:
    type: oci:identity:groups:id
    dependsOn:
      compartmentId: ${tenancy_ocid}
    title: "Existing Storage Admin group name"
    description: "Existing group to which Storage management policies will be granted to."
    visible: use_existing_groups  

  deploy_dynamic_groups:
    type: boolean
    title: "Deploy Dynamic Groups?"
    description: "Whether dynamic groups should be deployed. When checked, one set with four dynamic groups is created for each compartment specified in \"Enclosing Compartment Names\". For the dynamic group names, see <a href=\"https://github.com/oracle-quickstart/oci-cis-landingzone-quickstart/blob/main/VARIABLES.md#dynamic_group_names\">Dynamic Group Names"</a>. When unchecked, no dynamic groups are created.
    default: true
    required: true

  tenancy_ocid:
    type: string

  user_ocid:
    type: string

  fingerprint:
    type: string

  private_key_path:
    type: string

  private_key_password:
    type: password

outputs:
  release:
    type: string
    title: CIS Landing Zone Release

  home_region:
    type: string
    title: Home Region

  unique_prefix:
    type: string
    title: Unique Prefix

  lz_top_compartments:
    type: json
    title: Compartments (use these as existing enclosing compartments for deploying CIS Landing Zones) 

  lz_provisioning_groups:
    type: json
    title: Provisioning Groups (use these to provision CIS Landing Zones in the respective compartment)

  lz_groups:
    type: json
    title: Management Groups (use these as existing groups when deploying CIS Landing Zones)

  lz_dynamic_groups:
    type: json
    title: Dynamic Groups (use these as existing dynamic groups when deploying CIS Landing Zones)  

outputGroups:
  - title: Outputs
    outputs:
      - ${release}
      - ${home_region}
      - ${unique_prefix}
      - ${lz_top_compartments}
      - ${lz_provisioning_groups}
      - ${lz_groups}
      - ${lz_dynamic_groups}