variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "private_key_password" {}
variable "region" {}
variable "service_label" {}
variable "network_admin_email_endpoint" {}
variable "security_admin_email_endpoint" {}
