# Copyright (c) 2020 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "OCI CIS Landing Zone Stack"
stackDescription: "A Resource Manager Stack to deploy a set of CIS compliant resources in an OCI tenancy."
schemaVersion: 1.1.0
version: "20210326"
locale: "en"

variableGroups:
  - title: "Environment"
    variables:
      - "region"
      - "service_label"

  - title: "Network"
    variables:
      - "vcn_cidr"
      - "public_subnet_cidr"
      - "private_subnet_app_cidr"
      - "private_subnet_db_cidr"
      - "public_src_bastion_cidr"
      - "public_src_lbr_cidr"
      - "is_vcn_onprem_connected"
      - "onprem_cidr"

  - title: "Notifications"
    variables:
      - "network_admin_email_endpoint"
      - "security_admin_email_endpoint"

  - title: "Cloud Guard"
    variables:
      - "cloud_guard_configuration_status"

  - title: "Service Connector Hub For Audit Logs"
    variables:
      - "create_service_connector_audit"
      - "service_connector_audit_target"
      - "service_connector_audit_state"
      - "service_connector_audit_target_OCID"
      - "service_connector_audit_target_cmpt_OCID"
      - "sch_audit_target_rollover_MBs"
      - "sch_audit_target_rollover_MSs"
      - "sch_audit_objStore_objNamePrefix"


  - title: "Service Connector Hub For VCN Flow Logs"
    variables:
      - "create_service_connector_vcnFlowLogs"
      - "service_connector_vcnFlowLogs_target"
      - "service_connector_vcnFlowLogs_state"
      - "service_connector_vcnFlowLogs_target_OCID"
      - "service_connector_vcnFlowLogs_target_cmpt_OCID"
      - "sch_vcnFlowLogs_target_rollover_MBs"
      - "sch_vcnFlowLogs_target_rollover_MSs"
      - "sch_vcnFlowLogs_objStore_objNamePrefix"

  - title: "Vulnerability Scanning"
    variables:
      - "vss_create"
      - "vss_scan_schedule"
      - "vss_scan_day"
   
  - title: "Hidden Variables"
    visible: false
    variables:
      - "user_ocid"
      - "fingerprint"
      - "private_key_path"
      - "private_key_password"

variables:

  tenancy_ocid:
    type: string
    visible: false

  service_label:
    type: string
    title: "Service Label"
    minLength: 1
    maxLength: 127
    pattern: "^[A-Za-z][A-Za-z0-9]{1,7}$"
    description: "A unique label that gets prepended to all resources created by the Landing Zone."
    required: true

  region:
    type: oci:identity:region:name
    title: "Region"
    description: "The region for resources deployment."
    required: true
  
  vcn_cidr:
    type: string
    title: "VCN CIDR IP Range"
    required: true
    default: "10.0.0.0/16"
    pattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
    description: "Network IP range in CIDR notation."

  public_subnet_cidr:
    type: string
    title: "Public Subnet IP Range"
    required: true
    default: "10.0.1.0/24"
    pattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
    description: "IP range of public subnet in CIDR notation. It must be in VCN CIDR range."

  private_subnet_app_cidr:
    type: string
    title: "Private Application Subnet IP Range"
    required: true
    default: "10.0.2.0/24"
    pattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
    description: "IP range of application subnet in CIDR notation. It must be in VCN CIDR range."

  private_subnet_db_cidr:
    type: string
    title: "Private Database Subnet IP Range"
    required: true
    default: "10.0.3.0/24"
    pattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
    description: "IP range of database subnet in CIDR notation. It must be in VCN CIDR range."

  public_src_bastion_cidr:
    type: string
    title: "Bastion Grant IP Range"
    required: true
    pattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
    description: "External IP range allowed to connect to bastion host. It must not be 0.0.0.0/0."

  public_src_lbr_cidr:
    type: string
    title: "Load Balancer Grant IP Range"
    required: true
    pattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
    description: "External IP range allowed to connect to the VCN public subnet over the http protocol."

  is_vcn_onprem_connected:
    type: boolean
    title: "Connect to On-Premises Network?"
    default: false

  onprem_cidr:
    type: string
    title: "On-Premises Network CIDR"
    pattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
    visible: is_vcn_onprem_connected
    required: is_vcn_onprem_connected
    description: "IP range of your on-premises network in CIDR notation. It must not overlap with VCN CIDR IP Range and must not be the same as Load Balancer Grant IP Range."

  network_admin_email_endpoint:
    type: string
    title: "Network Admin Email Address"
    pattern: "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$"
    required: true
    description: "Recipient for all network notifications."

  security_admin_email_endpoint:
    type: string
    title: "Security Admin Email Address"
    pattern: "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$"
    required: true
    description: "Recipient for all securtiy notifications."

  cloud_guard_configuration_status:
    type: enum
    title: "Cloud Guard Configuration Status"
    description: "Whether or not to activate Cloud Guard as part of Landing Zone deployment."
    enum:
      - ENABLED
      - DISABLED

  # Service Connector Hub For Audit Logs - Variables
  create_service_connector_audit:
    type: boolean
    required: true
    title: "Create Service Connector Hub for Audit Logs (This might incur some cost)"
    description: "Create Service Connector Hub for Audit logs. Costs associated are due to storing objects in object storage / streaming or function invocations."
    default: false

  service_connector_audit_target:
    type: enum
    required: false
    title: "Service Connector Hub Target"
    description: "Destination for Service Connector Hub for Audit Logs. Select one of - objectstorage, streaming or functions."
    default: objectstorage
    visible: create_service_connector_audit
    enum:
      - objectstorage
      - streaming
      - functions

  service_connector_audit_state:
    type: enum
    required: false
    title: "Service Connector Hub State"
    description: "State in which to create the Service Connector Hub for Audit logs."
    default: INACTIVE
    visible: create_service_connector_audit
    enum:
      - INACTIVE
      - ACTIVE

  service_connector_audit_target_OCID:
    type: string
    required: false
    title: "Target Stream/Function OCID"
    description: "Applicable only for streaming/functions target types. OCID of stream/function target for the Service Connector Hub for Audit logs."
    visible: 
      and:
        - ${create_service_connector_audit}
        - or:
          - eq:
            - service_connector_audit_target
            - "streaming"
          - eq:
            - service_connector_audit_target
            - "functions"

  service_connector_audit_target_cmpt_OCID:
    type: string
    required: false
    title: "Target Stream/Function Compartment OCID"
    description: "Applicable only for streaming/functions target types. OCID of compartment containing the stream/function target for the Service Connector Hub for Audit logs."
    visible: 
      and:
        - ${create_service_connector_audit}
        - or:
          - eq:
            - service_connector_audit_target
            - "streaming"
          - eq:
            - service_connector_audit_target
            - "functions"

  sch_audit_objStore_objNamePrefix:
    type: string
    required: false
    title: "Object Name Prefix for Object Storage Target"
    description: "Applicable only for objectstorage target type. The prefix for the objects for Audit logs."
    default: "sch-audit"
    visible: 
      and:
        - ${create_service_connector_audit}
        - eq:
          - service_connector_audit_target
          - "objectstorage"


  # Service Connector Hub For VCN Flow Logs - Variables
  create_service_connector_vcnFlowLogs:
    type: boolean
    required: true
    title: "Create Service Connector Hub for VCN Flow Logs (This might incur some cost)"
    description: "Create Service Connector Hub for VCN Flow logs. Costs associated are due to storing objects in object storage / streaming or function invocations."
    default: false

  service_connector_vcnFlowLogs_target:
    type: enum
    required: false
    title: "Service Connector Hub Target"
    description: "Destination for Service Connector Hub for VCN Flow Logs. Select one of - objectstorage, streaming or functions."
    default: objectstorage
    visible: create_service_connector_vcnFlowLogs
    enum:
      - objectstorage
      - streaming
      - functions

  service_connector_vcnFlowLogs_state:
    type: enum
    required: false
    title: "Service Connector Hub State"
    description: "State in which to create the Service Connector Hub for VCN Flow logs."
    default: INACTIVE
    visible: create_service_connector_vcnFlowLogs
    enum:
      - INACTIVE
      - ACTIVE

  service_connector_vcnFlowLogs_target_OCID:
    type: string
    required: false
    title: "Target Stream/Function OCID"
    description: "Applicable only for streaming/functions target types. OCID of stream/function target for the Service Connector Hub for VCN Flow logs."
    visible: 
      and:
        - ${create_service_connector_vcnFlowLogs}
        - or:
          - eq:
            - service_connector_vcnFlowLogs_target
            - "streaming"
          - eq:
            - service_connector_vcnFlowLogs_target
            - "functions"

  service_connector_vcnFlowLogs_target_cmpt_OCID:
    type: string
    required: false
    title: "Target Stream/Function Compartment OCID"
    description: "Applicable only for streaming/functions target types. OCID of compartment containing the stream/function target for the Service Connector Hub for VCN Flow logs."
    visible: 
      and:
        - ${create_service_connector_vcnFlowLogs}
        - or:
          - eq:
            - service_connector_vcnFlowLogs_target
            - "streaming"
          - eq:
            - service_connector_vcnFlowLogs_target
            - "functions"

  sch_vcnFlowLogs_objStore_objNamePrefix:
    type: string
    required: false
    title: "Object Name Prefix for Object Storage Target"
    description: "Applicable only for objectstorage target type. The prefix for the objects for VCN Flow logs."
    default: "sch-vcnFlowLogs"
    visible: 
      and:
        - ${create_service_connector_vcnFlowLogs}
        - eq:
          - service_connector_vcnFlowLogs_target
          - "objectstorage"
  
  # Vulnerability Scanning
  vss_create:
    type: boolean
    title: "Enable Vulnerability Scanning?"
    description: "Whether or not Vulnerability Scanning is enabled. If checked, a scanning recipe is created and scanning targets are created for each Landing Zone compartment."
    default: true

  vss_scan_schedule:
    type: enum
    title: "Scanning Schedule"
    description: "When to scan. Weekly or daily."
    default: WEEKLY
    visible: vss_create
    enum:
      - WEEKLY
      - DAILY

  vss_scan_day:
    type: enum
    title: "Scanning Day"
    description: "The day when to scan. Only applies to weekly scans."
    default: SUNDAY
    enum:
      - SUNDAY
      - MONDAY
      - TUESDAY
      - WEDNESDAY
      - THURSDAY
      - FRIDAY
      - SATURDAY 
    visible:
      and:
        - ${vss_create}
        - eq:
          - vss_scan_schedule
          - "WEEKLY"
    
  # Variables not required to display to user
  user_ocid:
    type: string

  fingerprint:
    type: string

  private_key_path:
    type: string

  private_key_password:
    type: password
